// <auto-generated />
using CreatingModel_MsSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CreatingModel_MsSQL.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20171003180818_migrations")]
    partial class migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreatingModel_MsSQL.CodeFirstContext+Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("CreatingModel_MsSQL.CodeFirstContext+AuthorImage", b =>
                {
                    b.Property<int>("AuthorImageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<byte[]>("Image");

                    b.Property<string>("Title");

                    b.HasKey("AuthorImageId");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.ToTable("ImageByAuthor");
                });

            modelBuilder.Entity("CreatingModel_MsSQL.CodeFirstContext+Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Title");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CreatingModel_MsSQL.CodeFirstContext+BookAuthor", b =>
                {
                    b.Property<int>("BookId");

                    b.Property<int>("AuthorId");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BooksAuthors");
                });

            modelBuilder.Entity("CreatingModel_MsSQL.CodeFirstContext+AuthorImage", b =>
                {
                    b.HasOne("CreatingModel_MsSQL.CodeFirstContext+Author", "Author")
                        .WithOne("AuthorImage")
                        .HasForeignKey("CreatingModel_MsSQL.CodeFirstContext+AuthorImage", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CreatingModel_MsSQL.CodeFirstContext+BookAuthor", b =>
                {
                    b.HasOne("CreatingModel_MsSQL.CodeFirstContext+Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CreatingModel_MsSQL.CodeFirstContext+Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
